/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Chat;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.LinksChats;
import edu.java.domain.jooq.tables.records.ChatRecord;
import edu.java.domain.jooq.tables.records.LinkRecord;
import edu.java.domain.jooq.tables.records.LinksChatsRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] { Chat.CHAT.CHAT_ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.LINK_ }, true);
    public static final UniqueKey<LinksChatsRecord> CONSTRAINT_4 = Internal.createUniqueKey(LinksChats.LINKS_CHATS, DSL.name("CONSTRAINT_4"), new TableField[] { LinksChats.LINKS_CHATS.CHAT_ID, LinksChats.LINKS_CHATS.LINK }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinksChatsRecord, ChatRecord> CONSTRAINT_45 = Internal.createForeignKey(LinksChats.LINKS_CHATS, DSL.name("CONSTRAINT_45"), new TableField[] { LinksChats.LINKS_CHATS.CHAT_ID }, Keys.CONSTRAINT_1, new TableField[] { Chat.CHAT.CHAT_ID }, true);
    public static final ForeignKey<LinksChatsRecord, LinkRecord> CONSTRAINT_453 = Internal.createForeignKey(LinksChats.LINKS_CHATS, DSL.name("CONSTRAINT_453"), new TableField[] { LinksChats.LINKS_CHATS.LINK }, Keys.CONSTRAINT_2, new TableField[] { Link.LINK.LINK_ }, true);
}
